basic:
    name: 'Fischer Engineering'
    environments:
        production: 'https://master-7rqtwti-ylh5xhww2twj4.de-2.platformsh.site/'
        staging: ''
        development: ''
    breakpoints:
        - 360
        - 820
        - 1440
    pages:
        - /
        - /referenzen
        - /referenzen/mettlenweg-biel
        - /dienstleistungen/sicherheit
        - /ueber-uns/kontaktpersonen
        - /ueber-uns/geschichte
        - /jobs/stellen
        - /jobs/lehrlinge
        - /kontakt
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 0
    scroll: false
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: "if (window.location.search != '?cookie') {\n  jQuery('#sliding-popup').remove()\n}"
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    sensitivity: 15
    night_mode: false
    retina_images: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: false
proxy: false
type: single-site
